version: '3.8'

services:
  app:
    image: phonebook-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 3000:3000
    container_name: phonebook-frontend-dev
    tty: true


  backend:
    image: phonebook-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 3001:3001
    container_name: backend-dev

